Update actionsBuild.yml

diff --git a/.github/workflows/actionsBuild.yml b/.github/workflows/actionsBuild.yml
--- a/.github/workflows/actionsBuild.yml
+++ b/.github/workflows/actionsBuild.yml
@@ -24,7 +24,15 @@ jobs:
       run: mvn package --file liquibase-couchbase/pom.xml -DskipTests
     
     - name: Test with Maven
-      run: mvn clean verifyy --file liquibase-couchbase/pom.xml -Dskip.integration.tests=false
+      run: mvn clean verify --file liquibase-couchbase/pom.xml -Dskip.integration.tests=false
+      
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: JEST Tests            # Name of the check run which will be created
+        path: reports/jest-*.xml    # Path to test results
+        reporter: jest-junit        # Format of test results
 
 #     # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
 #     - name: Update dependency graph
